### ISSUE TITLE
Segment Integration

### ISSUE THREAD

**Issue by dikaio** [stueccles/analytics-elixir#1]
Hi Stuart. Please forgive me ahead of time for what is probably obvious answer to my question.

Where are you adding the tracking code ([Track](https://github.com/stueccles/analytics-elixir#track), [Identify](https://github.com/stueccles/analytics-elixir#identify), etc. )? Would that be the view?

Many thanks!

**Comment by stueccles** [comment]
Hi dikalo,

My preference is always to add serverside tracking code closest to where the action actually took place. This is usually the controller but in reality is going to be in function where you are doing business logic
