### ISSUE TITLE
Publish 0.1.2 to hex?

### ISSUE THREAD

**Issue by joshsmith** [stueccles/analytics-elixir#12]
Thanks for merging in some of those PRs today! Is there any chance we could push an update to hex for the version bump?

**Comment by begedin** [comment]
A reminder here as well, #10 is a fix for #7 and it's on master, but 0.1.2 is not released so the only way to get it is to target a direct commit hash or branch instead of a hex package. Any chance of publishing the next version, or granting someone the credentials to publish.

**Comment by stueccles** [comment]
i've picked this back up now and published 0.1.2 to hex. probably too late to be useful now but since I still own the hex for segment i can update it.
