### ISSUE TITLE
Async race condition

### ISSUE THREAD

**Issue by craiglyons** [stueccles/analytics-elixir#16]
Due to the async nature of calls to the Segment API, events that are fired close together can arrive simultaneously or out of order.
For example, this is an issue for an `identify` event followed immediately by a `track` event - frequently, the `track` event ends up without any of the related user data provided by `identify` in instruments such as Amplitude.

Since events return a `Task`, this could be handled at the call site by awaiting the first event, but this solution feels a little weird since the `await` also belongs in a separate process of its own so as not to block. 

Any suggestions for a workaround or an API to support synchronous events in the package?
I'm happy to put some effort into it.

**Comment by stueccles** [comment]
hi @craiglyons. version 0.2.0 now supports using the `batch` API at Segment to FIFO queue and batch events to segment. i'm not 100% sure that when using the batch that segment respects the order, but i think this might help.
