### ISSUE TITLE
Feature: Support additional fields

### ISSUE THREAD

**Issue by mmartinson** [stueccles/analytics-elixir#19]
Using [the python client](https://segment.com/docs/sources/server/python/) as a reference, there are some fields that aren't supported. I need support for `timestamp` specifically, but it would be helpful to support all the fields that the standard clients to.

in addition to existing `user_id`, `event`, `properties` and `context`, we'd need to support `timestamp`, `anonymous_id`, and `integrations`.

Looking at the official SDKs, it looks like they take a ton of positional arguments, which I find to be awkward and error prone, since some may not be used in many cases. Proposal for this is to add a `Segment.Event` data structure, with supporting functions to add fields into the event using a pipeline. The code is the caller's app may look as follows:

```
defmodule MyApp.UserAnalytics do
  import Segment.Event

  def track(user_id, :my_app_event, data) do
    Segment.Event
    |> add_type("My App Event")
    |> add_context(%{locale: "en-US"})
    |> add_timestamp(data.inserted_at)
    |> Segment.Analytics.track()
  end
end
```

With this, we'd add 1-arity version of the functions in `Segment.Analytics`, which would easily map into the existing internal structs there.

I can do this, just want to throw it up for some feedback first.

**Comment by mmartinson** [comment]
Reading the codebase closer, I see much of this is already implemented.

**Comment by stueccles** [comment]
Hi mike, 

All of those features are supported in the `0.2.0` library by creating a struct with the relevant attributes

```
%Segment.Analytics.Track{  event: "My App Event",  
                                                timestamp: data.inserted_at, 
                                                integrations: %{
                                                   all: true,
                                                   salesforce: false,
                                                } 
}  |> Segment.Analytics.track()
```
Your proposal just adds a different method of creating the struct, so i'm not sure its *needed*. I'll leave this open and see if anyone else thinks this is needed.
