### ISSUE TITLE
0.2.0 doesn't work with distillery releases

### ISSUE THREAD

**Issue by jfrolich** [stueccles/analytics-elixir#21]
It fails to start with the app. These are my logs:

```
(segment) lib/segment/batcher.ex:33: Segment.Analytics.Batcher.start_link/1
Tesla.client([{Tesla.Middleware.BaseUrl, "https://api.segment.io/v1/"}, Tesla.Middleware.JSON, {Tesla.Middleware.BasicAuth, %{password: "", username: "<REDACTED>"}}], {Tesla.Adapter.Hackney, [recv_timeout: 30000]})
** (UndefinedFunctionError) function Tesla.client/2 is undefined (module Tesla is not available)
** (EXIT) an exception was raised:
05:30:19.685 [info] Application family_five exited: FamilyFive.Application.start(:normal, []) returned an error: shutdown: failed to start child: Segment
Kernel pid terminated (application_controller) ({application_start_failure,family_five,{{shutdown,{failed_to_start_child,'Elixir.Segment',{'EXIT',{undef,[{'Elixir.Tesla',client,[[{'Elixir.Tesla.Middle
{"Kernel pid terminated",application_controller,"{application_start_failure,family_five,{{shutdown,{failed_to_start_child,'Elixir.Segment',{'EXIT',{undef,[{'Elixir.Tesla',client,[[{'Elixir.Tesla.Middleware.BaseUrl',<<\"https://api.segment.io/v1/\">>},'Elixir.Tesla.Middleware.JSON',{'Elixir.Tesla.Middleware.BasicAuth',#{password => <<>>,username => <<\"VuwApBWk0NccFDgpcFhCvnf1sDOOxZbc\">>}}],{'Elixir.Tesla.Adapter.Hackney',[{recv_timeout,30000}]}],[]},{'Elixir.Segment.Analytics.Batcher',start_link,1,[{file,\"lib/segment/batcher.ex\"},{line,33}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,379}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,349}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1157}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,315}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]}]}}}},{'Elixir.FamilyFive.Application',start,[normal,[]]}}}"}
Crash dump is being written to: erl_crash.dump...done
```

Not a great deal of time to research this, so I rolled it back to the old version which works fine. It works when starting with mix, so I guess it has something to do with running elixir as a release.

**Comment by stueccles** [comment]
I have run `0.2.0` in production with a phoenix deployment using Elixir 1.9 releases so im not sure it is that. It is possible if you are using Elixir < 1.3 you need to add Tesla to your `applications` in `mix.exs` to ensure it is loaded? this would cause something like this.

But aside from that can you let me know what version of Distillary and elixir you are using?

**Comment by jfrolich** [comment]
Distillery 2.1 and Elixir 1.9.

**Comment by stueccles** [comment]
So, unlike `mix release` in Elixir 1.9. Distillery doesn't include applications that are not specifically declared in the mix file. to fix this you can just add `:tesla` and `:jason` to `extra_applications` in your mix config and it will work (I just tested it). 

I've also put out a `0.2.1` release which includes these applications so you dont need to be explicit in your application and other people wont run into this.

**Comment by jfrolich** [comment]
> So, unlike `mix release` in Elixir 1.9. Distillery doesn't include applications that are not specifically declared in the mix file. to fix this you can just add `:tesla` and `:jason` to `extra_applications` in your mix config and it will work (I just tested it).
> 
> I've also put out a `0.2.1` release which includes these applications so you dont need to be explicit in your application and other people wont run into this.

Ah good to know. Didn't know about that. Thanks for the fix!
