### ISSUE TITLE
 Avoid compile-time application configuration 

### ISSUE THREAD

**Issue by Domeee** [stueccles/analytics-elixir#24]
First and foremost, thanks so much for this library!

I was just toying around with my application and segment when I realized that this library uses compile time configuration. Although I changed my segment configuration from `send_to_http: true` to `send_to_http: false` the behavior remained the same. I had to recompile the application with all dependencies to apply the configuration change. This behavior is listed as a anti-pattern in the official Elixir docs for libraries: https://hexdocs.pm/elixir/library-guidelines.html#avoid-compile-time-application-configuration

If you are interested I can write a PR to change the compile time configuration to runtime based configuration (as proposed in the Elixir docs). 

Regards,
Dominique

**Comment by stueccles** [comment]
yep you are right on this. I've been moving to purely runtime config everywhere but this is hangup from when i first wrote it. 

happy to accept a PR, otherwise i'll get to this in the next few weeks
