### ISSUE TITLE
Releasing on hex?

### ISSUE THREAD

**Issue by JoshSmith** [stueccles/analytics-elixir#4]
I saw that a hex package was published awhile ago that does not bring in changes from this repository.

Do you have any intention of releasing on hex so that dependency management for projects that rely on this becomes a bit easier?

https://hex.pm/docs/publish

Thanks!

**Comment by stueccles** [comment]
@JoshSmith Done. Although I'm going to do a little rewrite soon so there may be changes going forward.

**Comment by JoshSmith** [comment]
Thank you!
