### ISSUE TITLE
Best practices re: testing / dev mode

### ISSUE THREAD

**Issue by jeffdeville** [stueccles/analytics-elixir#5]
Hey Stuart, thought I'd check and see how you use the package in dev and test mode. Analytics is pretty central for what I do, so testing will be critical. As a result, I was considering creating multiple logging strategies, but wanted to see if you'd already come up with a simpler solution.

My first thought was to create multiple strategies.  In production, that strategy would be what you already have. The HTTP api.  In Dev, it would probably just log to the console, and in Test, I was thinking about writing to an in memory data store (an Agent Array) or something.  

Any thoughts / suggestions?

Thanks!

**Comment by JoshSmith** [comment]
@jeffdeville you can see what we do in https://github.com/code-corps/code-corps-api/tree/develop/lib/code_corps/analytics for some inspiration, if you'd like.

**Comment by stueccles** [comment]
Hey @jeffdeville I pattern I've used since is injecting the implementation as configuration and just log to console or a file. I will rewrite to enable this pattern

**Comment by jeffdeville** [comment]
Thanks for the insight, guys!

**Comment by stueccles** [comment]
version 0.2.0 now supports overriding the Adapter for this kind of testing. you can also just `config :segment, send_to_http: false` if you just want to log to debug
