### ISSUE TITLE
Function clause error during `log_result` in the case of HTTPoison timeout error

### ISSUE THREAD

**Issue by begedin** [stueccles/analytics-elixir#7]
In our production environment, sentry logged a couple of errors which seem to be internal to the Segment library.

They are function clause errors and they happen when calling `log_result`. It's being called with the following parameters:

```Elixir
Segment.Analytics.log_result(
  {:error, %HTTPoison.Error{id: nil, reason: :timeout}}, 
  "identify",
  %{}  # this is a trait map, which I omitted
)
```

Apparently, `log_result`has no matcher for a `HTTPoison.Error` struct. Should it be added, or should we expect the library to throw an error here?

**Comment by JoshSmith** [comment]
@stueccles any thoughts on this?

**Comment by stueccles** [comment]
the error handling needs to be better here. pattern matching errors are not useful here. i would expect the library to throw an error here to be handled in calling code. 

I checked out https://github.com/code-corps/code-corps-api/issues/688 and its worth noting you might have an issue with your pool sizing. We have seen similar timeout errors in production.

**Comment by begedin** [comment]
#10 resolves this issue, but the next hext version (as requested in #12 has not been released. 

If the current contributors don't have the time, which is perfectly acceptable, any chance of adding someone else on board. I don't have much time either, but I could deal with minor maintenance at least.
